name: Build Zip

on:
  push:
    tags:
      - "*"
jobs:
  release:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create zip
        run: |
          zip -r filter_and_sounds.zip . -x .github/** -x .git/** -x filtersounds.zip
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: filter-and-sounds
          path: |
            filter_and_sounds.zip
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          omitBody: true
          artifacts: "filter_and_sounds.zip"
          makeLatest: true
